set(Curl_VERSION "7.62.0")
set(prefix "${PROJECT_SOURCE_DIR}/external/lib/curl-${Curl_VERSION}") 
set(Curl_INCLUDE_DIRS "${prefix}/include")

if (MSYS OR MINGW)
    if (prefix)
        if (NOT EXISTS ${prefix})
            message(FATAL_ERROR "CURL directory not found: " ${prefix})
        endif()
    endif()

    set(exec_prefix "${prefix}")
    set(libdir "${exec_prefix}/lib")
    set(Curl_LIBDIR "${exec_prefix}/lib")
    #set(Curl_LIBRARIES "-lcurl")
    #string(STRIP "${Curl_LIBRARIES}" Curl_LIBRARIES)
elseif (APPLE)
    set(Curl_LIBRARIES "-framework curl")
else()
    PKG_SEARCH_MODULE(CURL REQUIRED curl)
    string(STRIP "${Curl_LIBRARIES}" Curl_LIBRARIES)
endif()
