if (MSYS OR MINGW)
    set(SDL2_VERSION "2.0.14")
    set(prefix "${PROJECT_SOURCE_DIR}/external/lib/mingw/SDL2-${SDL2_VERSION}/x86_64-w64-mingw32") 
    if (prefix)
        if (NOT EXISTS ${prefix})
            message(FATAL_ERROR "SDL2 directory not found: " ${prefix})
        endif()
    endif()

    set(exec_prefix "${prefix}")
    set(libdir "${exec_prefix}/lib")
    #set(SDL2_PREFIX "/usr/local/cross-tools/i686-w64-mingw32")
    #set(SDL2_EXEC_PREFIX "/usr/local/cross-tools/i686-w64-mingw32")
    set(SDL2_LIBDIR "${exec_prefix}/lib")
    set(SDL2_INCLUDE_DIRS "${prefix}/include/SDL2")
    set(SDL2_LIBRARIES "-lmingw32 -lSDL2main -lSDL2  -mwindows")
    string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
elseif (APPLE)
    FIND_PATH(SDL2_INCLUDE_DIRS SDL2/SDL.h)
    if (NOT EXISTS ${SDL2_INCLUDE_DIRS})
        message(FATAL_ERROR "SDL2 framework not found")
    endif()

    set(SDL2_LIBRARIES "-framework SDL2")
else()
    PKG_SEARCH_MODULE(SDL2 REQUIRED sdl2)
    string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
endif()
